// Datos hardcodeados para el MVP
import type { CentroCosto, SurtidorExtended } from "../types";
export const mockUser = {
  id: 1,
  nombre: "Juan",
  apellido: "Pérez",
  email: "admin@empresa.com",
  rol: "Admin",
  empresaId: 1,
  empresa: "AgroTransporte SA",
};

export const mockSurtidores: SurtidorExtended[] = [
  {
    id: 1,
    codigo: "SUR-001",
    nombre: "Surtidor Principal",
    ubicacion: "Estación Central",
    tipoCombustible: "Diésel",
    empresaId: 1,
    empresa: "AgroTransporte SA",
    activo: true,
  },
  {
    id: 2,
    codigo: "SUR-002",
    nombre: "Surtidor Campo Norte",
    ubicacion: "Lote 45",
    tipoCombustible: "Diésel",
    empresaId: 1,
    empresa: "AgroTransporte SA",
    activo: true,
  },
  {
    id: 3,
    codigo: "SUR-003",
    nombre: "Surtidor Nave 3",
    ubicacion: "Planta Industrial",
    tipoCombustible: "Nafta",
    empresaId: 2,
    empresa: "Transportes del Sur",
    activo: false,
  },
];


// --- CORRIGE EL TIPO DE mockCentrosCosto ---
export const mockCentrosCosto: CentroCosto[] = [
  {
    id: 1,
    codigo: "LOTE-05B",
    nombre: "Lote 5B - Maíz",
    tipo: "Lote",
    activo: true,
    empresaId: 1,
    empresaNombre: "AgroTransporte SA",
  },
  {
    id: 2,
    codigo: "OBRA-RP9",
    nombre: "Obra Ruta Provincial 9",
    tipo: "Obra",
    activo: true,
    empresaId: 2,
    empresaNombre: "Logística del Sur",
  },
  {
    id: 3,
    codigo: "AREA-MANT",
    nombre: "Mantenimiento General",
    tipo: "Area",
    activo: true,
    empresaId: 1,
    empresaNombre: "AgroTransporte SA",
  },
  {
    id: 4,
    codigo: "PROY-AQUA",
    nombre: "Proyecto Aqua",
    tipo: "Proyecto",
    activo: false,
    empresaId: 2,
    empresaNombre: "Logística del Sur",
  },
];

export const mockSuperAdmin = {
  id: 999,
  nombre: "System",
  apellido: "Administrator",
  email: "superadmin@fuelsystem.com",
  rol: "SuperAdmin",
  empresaId: null,
  empresa: "Fuel Management Platform",
};

export const mockEmpresas = [
  {
    id: 1,
    nombre: "AgroTransporte SA",
    cuit: "30-12345678-9",
    tipoMercado: "Agro",
    activo: true,
  },
  {
    id: 2,
    nombre: "Logística del Sur",
    cuit: "30-87654321-0",
    tipoMercado: "Transporte",
    activo: true,
  },
  {
    id: 3,
    nombre: "Campo Verde SRL",
    cuit: "30-11223344-5",
    tipoMercado: "Agro",
    activo: false,
  },
];

export const mockUsuarios = [
  {
    id: 1,
    empresaId: 1,
    empresa: "AgroTransporte SA",
    nombre: "Juan",
    apellido: "Pérez",
    email: "juan@empresa.com",
    whatsapp: "+5493512345678",
    rol: "Admin",
    activo: true,
  },
  {
    id: 2,
    empresaId: 1,
    empresa: "AgroTransporte SA",
    nombre: "María",
    apellido: "González",
    email: "maria@empresa.com",
    whatsapp: "+5493518765432",
    rol: "Supervisor",
    activo: true,
  },
  {
    id: 3,
    empresaId: 1,
    empresa: "AgroTransporte SA",
    nombre: "Carlos",
    apellido: "Rodríguez",
    email: "carlos@empresa.com",
    whatsapp: "+5493519876543",
    rol: "Operador",
    activo: true,
  },
  {
    id: 4,
    empresaId: 2,
    empresa: "Logística del Sur",
    nombre: "Ana",
    apellido: "Martínez",
    email: "ana@logistica.com",
    whatsapp: "+5493513456789",
    rol: "Admin",
    activo: true,
  },
  {
    id: 5,
    empresaId: 2,
    empresa: "Logística del Sur",
    nombre: "Pedro",
    apellido: "López",
    email: "pedro@logistica.com",
    whatsapp: "+5493514567890",
    rol: "Operador",
    activo: true,
  },
];

export const mockVehiculos = [
  {
    id: 1,
    empresaId: 1,
    empresa: "AgroTransporte SA",
    patente: "ABC123",
    tipo: "Camión",
    marca: "Mercedes Benz",
    modelo: "Atego 1726",
    anio: 2020,
    capacidad: 300,
    activo: true,
  },
  {
    id: 2,
    empresaId: 1,
    empresa: "AgroTransporte SA",
    patente: "DEF456",
    tipo: "Tractor",
    marca: "John Deere",
    modelo: "6110J",
    anio: 2019,
    capacidad: 250,
    activo: true,
  },
  {
    id: 3,
    empresaId: 2,
    empresa: "Logística del Sur",
    patente: "GHI789",
    tipo: "Camión",
    marca: "Scania",
    modelo: "R450",
    anio: 2021,
    capacidad: 400,
    activo: true,
  },
  {
    id: 4,
    empresaId: 1,
    empresa: "AgroTransporte SA",
    patente: "JKL012",
    tipo: "Sembradora",
    marca: "Apache",
    modelo: "27000",
    anio: 2018,
    capacidad: 180,
    activo: true,
  },
  {
    id: 5,
    empresaId: 2,
    empresa: "Logística del Sur",
    patente: "MNO345",
    tipo: "Camión",
    marca: "Iveco",
    modelo: "Tector",
    anio: 2017,
    capacidad: 280,
    activo: false,
  },
];

export const mockChoferes = [
  {
    id: 1,
    empresaId: 1,
    empresa: "AgroTransporte SA",
    nombre: "Roberto",
    apellido: "Sánchez",
    dni: "25123456",
    licencia: "B1234567",
    whatsapp: "+5493511234567",
    activo: true,
  },
  {
    id: 2,
    empresaId: 1,
    empresa: "AgroTransporte SA",
    nombre: "Diego",
    apellido: "Fernández",
    dni: "28765432",
    licencia: "B7654321",
    whatsapp: "+5493517654321",
    activo: true,
  },
  {
    id: 3,
    empresaId: 2,
    empresa: "Logística del Sur",
    nombre: "Luis",
    apellido: "Gómez",
    dni: "30987654",
    licencia: "B9876543",
    whatsapp: "+5493519876543",
    activo: true,
  },
  {
    id: 4,
    empresaId: 2,
    empresa: "Logística del Sur",
    nombre: "Pedro",
    apellido: "López",
    dni: "27456789",
    licencia: "B4567890",
    whatsapp: "+5493514567890",
    activo: false,
  },
];

export const mockEventos = [
  {
    id: 1,
    empresaId: 1,
    empresa: "AgroTransporte SA",
    fecha: "2025-10-28T08:30:00",
    vehiculo: "ABC123 - Mercedes Benz Atego",
    chofer: "Roberto Sánchez",
    litros: 280,
    costo: 168000,
    kmInicial: 45230,
    kmFinal: 45580,
    estado: "Pendiente",
    ruta: "Córdoba - Rosario",
  },
  {
    id: 2,
    empresaId: 1,
    empresa: "AgroTransporte SA",
    fecha: "2025-10-27T15:45:00",
    vehiculo: "DEF456 - John Deere 6110J",
    chofer: "Diego Fernández",
    litros: 180,
    costo: 108000,
    lote: "Lote 5B",
    labor: "Siembra",
    estado: "Validado",
  },
  {
    id: 3,
    empresaId: 2,
    empresa: "Logística del Sur",
    fecha: "2025-10-27T11:20:00",
    vehiculo: "GHI789 - Scania R450",
    chofer: "Luis Gómez",
    litros: 350,
    costo: 210000,
    kmInicial: 89450,
    kmFinal: 89920,
    estado: "Validado",
    ruta: "Buenos Aires - Mendoza",
  },
  {
    id: 4,
    empresaId: 1,
    empresa: "AgroTransporte SA",
    fecha: "2025-10-26T09:10:00",
    vehiculo: "ABC123 - Mercedes Benz Atego",
    chofer: "Roberto Sánchez",
    litros: 290,
    costo: 174000,
    kmInicial: 44890,
    kmFinal: 45230,
    estado: "Rechazado",
    ruta: "Rosario - Córdoba",
  },
];

export const dashboardKPIs = {
  consumoMensual: { litros: 8450, costo: 5070000, variacion: 12.5 },
  eventosPendientes: 3,
  vehiculosActivos: 18,
  eficiencia: { promedio: 28.5, status: "good" },
};

export const consumoPorVehiculo = [
  { vehiculo: "ABC123", litros: 1250 },
  { vehiculo: "GHI789", litros: 1180 },
  { vehiculo: "DEF456", litros: 980 },
  { vehiculo: "JKL012", litros: 850 },
  { vehiculo: "MNO345", litros: 720 },
];

export const consumoTemporal = [
  { fecha: "22/10", litros: 450 },
  { fecha: "23/10", litros: 520 },
  { fecha: "24/10", litros: 380 },
  { fecha: "25/10", litros: 610 },
  { fecha: "26/10", litros: 490 },
  { fecha: "27/10", litros: 550 },
  { fecha: "28/10", litros: 420 },
];
